@startuml
skinparam classAttributeIconSize 0

interface Notification {
  +send(message: string): void
}

class EmailNotification {
  +send(message: string): void
}

class SmsNotification {
  +send(message: string): void
}

class WhatsAppNotification {
  +send(message: string): void
}


Notification <|.. EmailNotification
Notification <|.. SmsNotification
Notification <|.. WhatsAppNotification

abstract class NotificationCreator {
  {abstract} +createNotification(): Notification
  +notify(message: string): void
}

class EmailCreator {
  +createNotification(): Notification
}

class SmsCreator {
  +createNotification(): Notification
}

class WhatsAppCreator {
  +createNotification(): Notification
}

NotificationCreator <|-- EmailCreator
NotificationCreator <|-- SmsCreator
NotificationCreator <|-- WhatsAppCreator

NotificationCreator ..> Notification : uses
EmailCreator ..> EmailNotification : creates
SmsCreator ..> SmsNotification : creates
WhatsAppCreator ..> WhatsAppNotification : creates
@enduml
