@startuml sinlgeton

class DatabaseConnection {
    - instance : DatabaseConnection
    - DatabaseConnection()
    + getInstance() : DatabaseConnection
    + executeQuery(query : String) : void
}

@enduml